name: materia_dart
description: A new Flutter package project.
version: 0.0.1
author: karabiner.inc
homepage: https://www.karabiner.tech/

environment:
  sdk: ">=2.0.0-dev.64.2 <3.0.0"

dependencies:
  http: ^0.12.0
  js: ^0.6.0

dev_dependencies:
  test: ^1.3.0
  build_runner: ^1.2.0
  build_web_compilers: ^1.1.0